version: '3'
services:
  postgres:
    image: postgres
    env_file:
      - dev.env

  app:
    image: "${CI_PIPELINE_ID}:${CI_BUILD_REF_NAME}"
    env_file:
      - dev.env
    depends_on:
      - postgres

