name: app
channels:
- conda-forge
dependencies:
- python=3.6
- psycopg2=2.7.4
- uwsgi=2.0.17.1
- pip:
  - django==2.1.2
  - djangorestframework==3.8.2
  - djangorestframework-simplejwt==3.2.3
  - flake8
  - coreapi==2.3.3
  - django-cors-headers==2.4.0
