# Generated by Django 2.1.2 on 2018-12-03 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('last_response_received', models.DateTimeField(blank=True, null=True, verbose_name='last_response_received')),
                ('secure', models.BooleanField(default=False, verbose_name='secure')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('system_serial_number', models.CharField(max_length=25, unique=True, verbose_name='system_serial_number')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['secure', '-last_response_received'],
            },
        ),
        migrations.CreateModel(
            name='AgentInstaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(max_length=25, verbose_name='os_type')),
                ('version', models.CharField(max_length=25, verbose_name='version')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='file')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='AgentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('agent_version', models.CharField(max_length=50, verbose_name='agent_version')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='ip_address')),
                ('os_type', models.CharField(max_length=50, verbose_name='os_type')),
                ('os_version', models.CharField(max_length=50, verbose_name='os_version')),
                ('system_manufacturer', models.CharField(max_length=50, verbose_name='system_manufacturer')),
                ('system_model', models.CharField(max_length=50, verbose_name='system_model')),
                ('system_type', models.CharField(max_length=50, verbose_name='system_type')),
                ('bios_version', models.CharField(max_length=50, verbose_name='bios_version')),
                ('antispyware_enabled', models.BooleanField(default=False, verbose_name='antispyware_enabled')),
                ('antispyware_signature_last_updated', models.CharField(max_length=50, verbose_name='antispyware_signature_last_updated')),
                ('antivirus_enabled', models.BooleanField(default=False, verbose_name='antivirus_enabled')),
                ('antivirus_signature_last_updated', models.CharField(max_length=50, verbose_name='antivirus_signature_last_updated')),
                ('behavior_monitor_enabled', models.BooleanField(default=False, verbose_name='behavior_monitor_enabled')),
                ('full_scan_age', models.CharField(max_length=50, verbose_name='full_scan_age')),
                ('quick_scan_age', models.CharField(max_length=50, verbose_name='quick_scan_age')),
                ('nis_enabled', models.BooleanField(default=False, verbose_name='nis_enabled')),
                ('nis_signature_last_updated', models.CharField(max_length=50, verbose_name='nis_signature_last_updated')),
                ('nis_signature_version', models.CharField(max_length=50, verbose_name='nis_signature_version')),
                ('on_access_protection_enabled', models.BooleanField(default=False, verbose_name='on_access_protection_enabled')),
                ('real_time_protection_enabled', models.BooleanField(default=False, verbose_name='real_time_protection_enabled')),
                ('disk_encryption_status', models.CharField(max_length=50, verbose_name='disk_encryption_status')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='api.Agent', verbose_name='agent')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('to', models.EmailField(blank=True, max_length=35, null=True, verbose_name='alert_to')),
                ('subject', models.CharField(max_length=100, verbose_name='alert_subject')),
                ('content', models.TextField(verbose_name='alert_content')),
                ('sent', models.BooleanField(default=False, verbose_name='alert_sent')),
                ('agent_responses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AgentResponse', verbose_name='agent_responses')),
                ('target_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Agent', verbose_name='target_machine')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='app_name')),
                ('vendor', models.CharField(blank=True, max_length=50, null=True, verbose_name='vendor')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='version')),
                ('install_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='install_date')),
                ('agent_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AgentResponse', verbose_name='agent_response')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='date_updated')),
                ('os_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='os_type')),
                ('os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='os_version')),
                ('system_manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='system_manufacturer')),
                ('system_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='system_model')),
                ('system_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='system_type')),
                ('bios_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='bios_version')),
                ('antispyware_enabled', models.BooleanField(default=True, verbose_name='antispyware_enabled')),
                ('antispyware_signature_last_updated', models.CharField(blank=True, max_length=50, null=True, verbose_name='antispyware_signature_last_updated')),
                ('antivirus_enabled', models.BooleanField(default=True, verbose_name='antivirus_enabled')),
                ('antivirus_signature_last_updated', models.CharField(blank=True, max_length=50, null=True, verbose_name='antivirus_signature_last_updated')),
                ('behavior_monitor_enabled', models.BooleanField(default=True, verbose_name='behavior_monitor_enabled')),
                ('full_scan_age', models.TextField(blank=True, max_length=50, null=True, verbose_name='full_scan_age')),
                ('quick_scan_age', models.TextField(blank=True, max_length=50, null=True, verbose_name='quick_scan_age')),
                ('nis_enabled', models.BooleanField(default=True, verbose_name='nis_enabled')),
                ('nis_signature_last_updated', models.CharField(blank=True, max_length=50, null=True, verbose_name='nis_signature_last_updated')),
                ('nis_signature_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='nis_signature_version')),
                ('on_access_protection_enabled', models.BooleanField(default=True, verbose_name='on_access_protection_enabled')),
                ('real_time_protection_enabled', models.BooleanField(default=True, verbose_name='real_time_protection_enabled')),
                ('disk_encryption_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='disk_encryption_status')),
            ],
        ),
        migrations.CreateModel(
            name='StartupApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='app_name')),
                ('command', models.CharField(blank=True, max_length=255, null=True, verbose_name='command')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('user', models.CharField(blank=True, max_length=150, null=True, verbose_name='app_user')),
                ('agent_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AgentResponse', verbose_name='agent_response')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
