# Generated by Django 2.1.2 on 2018-11-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitystandard',
            name='protection_status',
        ),
        migrations.AddField(
            model_name='securitystandard',
            name='disk_encryption_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='disk_encryption_status'),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='disk_encryption_status',
            field=models.CharField(max_length=50, verbose_name='disk_encryption_status'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='bios_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bios_version'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='system_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='system_model'),
        ),
    ]
