# Generated by Django 2.1.2 on 2018-11-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181127_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['secure', '-last_response_received']},
        ),
    ]
