# Generated by Django 2.1.2 on 2018-12-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181204_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['secure', '-is_active', '-last_response_received']},
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='antispyware_signature_last_updated',
            field=models.CharField(default=0, max_length=50, verbose_name='antispyware_signature_last_updated'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='antivirus_signature_last_updated',
            field=models.CharField(default=0, max_length=50, verbose_name='antivirus_signature_last_updated'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='full_scan_age',
            field=models.TextField(default=0, max_length=50, verbose_name='full_scan_age'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='nis_signature_last_updated',
            field=models.CharField(default=0, max_length=50, verbose_name='nis_signature_last_updated'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='quick_scan_age',
            field=models.TextField(default=0, max_length=50, verbose_name='quick_scan_age'),
        ),
    ]
