# Generated by Django 2.1.2 on 2018-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181129_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='alert_subject'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='to',
            field=models.EmailField(blank=True, max_length=35, null=True, verbose_name='alert_to'),
        ),
    ]
