# Generated by Django 2.1.2 on 2018-11-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181129_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitystandard',
            name='antispyware_enabled',
            field=models.BooleanField(default=True, verbose_name='antispyware_enabled'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='antivirus_enabled',
            field=models.BooleanField(default=True, verbose_name='antivirus_enabled'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='behavior_monitor_enabled',
            field=models.BooleanField(default=True, verbose_name='behavior_monitor_enabled'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='nis_enabled',
            field=models.BooleanField(default=True, verbose_name='nis_enabled'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='on_access_protection_enabled',
            field=models.BooleanField(default=True, verbose_name='on_access_protection_enabled'),
        ),
        migrations.AlterField(
            model_name='securitystandard',
            name='real_time_protection_enabled',
            field=models.BooleanField(default=True, verbose_name='real_time_protection_enabled'),
        ),
    ]
